# always start with version: 2 ...
version: 2

#Each job represents a phase in your Build-Test-Deploy process, so everything else is going to live under that key.
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/android:api-26-alpha #could we remove -alpha
    environment:
      #JVM_OPTS: -Xmx3200m
      JVM_OPTS: -Xmx4G # to max the memory 
    steps:
      - checkout
      - run: echo "NOW WE START OUR BUILD --MMD"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          #      - run:
          #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
          #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          # to build apk file ..
          name: generate apk
          command: ./gradlew assemble
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          # to upload apk file to circle ci server.
          path: app/build/outputs/apk/debug
          destination: debug
      - store_test_results:
          path: app/build/test-results
          destination: test-results/